{
 "title": "Dam Monitoring",
 "description": "Dam monitoring dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Water level",
   "type": "graph",
   "description": "Level of water in the dam, thresholds are reporter in the plot",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "lengthm", "label": "Height" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(timestamp, INTERVAL 2 HOUR) as \"time\",\n  value as \"Water level\"\nFROM waterLevel\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Flow rates",
   "type": "graph",
   "description": "Channels flow rates",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "flowcms", "label": "Flow rate" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(timestamp, INTERVAL 2 HOUR) as \"time\",\n  flowChannel AS metric,\n  value\nFROM flowRate\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Gates opening",
   "type": "bargauge",
   "description": "Gates opening level",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT value, CONCAT(UPPER(SUBSTRING(name,1,1)),LOWER(SUBSTRING(name,2))), tag\nFROM resource\nWHERE type=\"gate\""
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "singlestat",
   "description": "Dam alarm in case of critical level of water",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT value\n  FROM resource \n  WHERE type='alarm'"
    }
   ]
  }
 ]
}